name: Go
on: [push, pull_request]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      env:
        PKG_CONFIG_PATH: ${GOPATH}/src/github.com/bububa/WeWorkFinanceSDK/lib
        CGO_LDFLAGS_ALLOW: '-w' 
      run: go build -v ./...

    - name: Test
      env:
        PKG_CONFIG_PATH: ${GOPATH}/src/github.com/bububa/WeWorkFinanceSDK/lib
        CGO_LDFLAGS_ALLOW: '-w' 
        APPKEY: ${{ secrets.APPKEY }}
        SECRET: ${{ secrets.APP_SECRET }}
      run: go test -v ./...
