name: Go
on: [push, pull_request]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      env:
        CGO_LDFLAGS_ALLOW: '-w' 
      run: go build -v --ldflags '-L./lib' ./...

    - name: Test
      env:
        CGO_LDFLAGS_ALLOW: '-w' 
      run: go test -v --ldflags '-L./lib' ./...
